/*
    image-viewer
*/
export const ADD_IMAGES_LIST_TO_IMAGE_VIEWER     = 'ADD_IMAGES_LIST_TO_IMAGE_VIEWER'
export const CLEAR_IMAGES_LIST_FROM_IMAGE_VIEWER = 'CLEAR_IMAGES_LIST_FROM_IMAGE_VIEWER'
export const SET_CURRENT_IMAGE_OF_IMAGE_VIEWER   = 'SET_CURRENT_IMAGE_OF_IMAGE_VIEWER'


/*
    layers-list
*/
export const SHOW_IMAGE_VIEWER = 'SHOW_IMAGE_VIEWER'
export const HIDE_IMAGE_VIEWER = 'HIDE_IMAGE_VIEWER'

export const SHOW_MENU = 'SHOW_MENU'
export const HIDE_MENU = 'HIDE_MENU'


/*
    section-images-list
*/
export const GET_SECTION_IMAGES_LIST_FETCHING = 'GET_SECTION_IMAGES_LIST_FETCHING'
export const GET_SECTION_IMAGES_LIST_OK       = 'GET_SECTION_IMAGES_LIST_OK'
export const GET_SECTION_IMAGES_LIST_ERROR    = 'GET_SECTION_IMAGES_LIST_ERROR'

export const CLEAR_SECTION_IMAGES_LIST = 'CLEAR_SECTION_IMAGES_LIST'


/*
    slides-list
*/
export const GET_SLIDES_LIST_FETCHING = 'GET_SLIDES_LIST_FETCHING'
export const GET_SLIDES_LIST_OK       = 'GET_SLIDES_LIST_OK'
export const GET_SLIDES_LIST_ERROR    = 'GET_SLIDES_LIST_ERROR'
