/*
    image-viewer
*/
export const ADD_IMAGES_TO_IMAGE_VIEWER_IMAGES_LIST = 'ADD_IMAGES_TO_IMAGE_VIEWER_IMAGES_LIST'
export const CLEAR_IMAGES_FROM_IMAGE_VIEWER_IMAGES_LIST = 'CLEAR_IMAGES_FROM_IMAGE_VIEWER_IMAGES_LIST'
export const SET_CURRENT_IMAGE_OF_IMAGE_VIEWER = 'SET_CURRENT_IMAGE_OF_IMAGE_VIEWER'



/*
    images-list
*/
export const GET_IMAGES_LIST_FETCHING = 'GET_IMAGES_LIST_FETCHING'
export const GET_IMAGES_LIST_OK       = 'GET_IMAGES_LIST_OK'
export const GET_IMAGES_LIST_ERROR    = 'GET_IMAGES_LIST_ERROR'

export const DELETE_IMAGE_FETCHING = 'DELETE_IMAGE_FETCHING'
export const DELETE_IMAGE_OK       = 'DELETE_IMAGE_OK'
export const DELETE_IMAGE_ERROR    = 'DELETE_IMAGE_ERROR'

export const CLEAR_IMAGES_FROM_IMAGES_LIST   = 'CLEAR_IMAGES_FROM_IMAGES_LIST'
export const ADD_UPLOAD_IMAGE_TO_IMAGES_LIST = 'ADD_UPLOAD_IMAGE_TO_IMAGES_LIST'


/*
    layers
*/
export const SHOW_UPLOAD_IMAGES_LIST = 'SHOW_UPLOAD_IMAGES_LIST'
export const HIDE_UPLOAD_IMAGES_LIST = 'HIDE_UPLOAD_IMAGES_LIST'

export const SHOW_IMAGE_VIEWER = 'SHOW_IMAGE_VIEWER'
export const HIDE_IMAGE_VIEWER = 'HIDE_IMAGE_VIEWER'

export const SHOW_MODAL_SECTION_IMAGES_LIST = 'SHOW_MODAL_SECTION_IMAGES_LIST'
export const HIDE_MODAL_SECTION_IMAGES_LIST = 'HIDE_MODAL_SECTION_IMAGES_LIST'

export const SHOW_MODAL_SECTION = 'SHOW_MODAL_SECTION'
export const HIDE_MODAL_SECTION = 'HIDE_MODAL_SECTION'

export const SHOW_MODAL_SLIDE_IMAGES_LIST_FETCHING = 'SHOW_MODAL_SLIDE_IMAGES_LIST_FETCHING'
export const SHOW_MODAL_SLIDE_IMAGES_LIST_OK       = 'SHOW_MODAL_SLIDE_IMAGES_LIST_OK'
export const SHOW_MODAL_SLIDE_IMAGES_LIST_ERROR    = 'SHOW_MODAL_SLIDE_IMAGES_LIST_ERROR'

export const SHOW_MODAL_SLIDES_LIST = 'SHOW_MODAL_SLIDES_LIST'
export const HIDE_MODAL_SLIDES_LIST = 'HIDE_MODAL_SLIDES_LIST'


/*
	modal-images-list
*/
export const GET_MODAL_SECTION_IMAGES_LIST_FETCHING = 'GET_MODAL_SECTION_IMAGES_LIST_FETCHING'
export const GET_MODAL_SECTION_IMAGES_LIST_OK       = 'GET_MODAL_SECTION_IMAGES_LIST_OK'
export const GET_MODAL_SECTION_IMAGES_LIST_ERROR    = 'GET_MODAL_SECTION_IMAGES_LIST_ERROR'

export const GET_MODAL_SLIDES_LIST_FETCHING = 'GET_MODAL_SLIDES_LIST_FETCHING'
export const GET_MODAL_SLIDES_LIST_OK       = 'GET_MODAL_SLIDES_LIST_OK'
export const GET_MODAL_SLIDES_LIST_ERROR    = 'GET_MODAL_SLIDES_LIST_ERROR'

export const CLEAR_MODAL_IMAGES_LIST = 'CLEAR_MODAL_IMAGES_LIST'

export const SELECT_MODAL_IMAGE   = 'SELECT_MODAL_IMAGE'
export const UNSELECT_MODAL_IMAGE = 'UNSELECT_MODAL_IMAGE'


/*
    notifications-list
*/
export const ADD_NOTIFICATION  = 'ADD_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'


/*
    section-images-list
*/
export const GET_SECTION_IMAGES_LIST_FETCHING = 'GET_SECTION_IMAGES_LIST_FETCHING'
export const GET_SECTION_IMAGES_LIST_OK       = 'GET_SECTION_IMAGES_LIST_OK'
export const GET_SECTION_IMAGES_LIST_ERROR    = 'GET_SECTION_IMAGES_LIST_ERROR'

export const CLEAR_SECTION_IMAGES_LIST = 'CLEAR_SECTION_IMAGES_LIST'

export const DELETE_SECTION_IMAGE_FETCHING = 'DELETE_SECTION_IMAGE_FETCHING'
export const DELETE_SECTION_IMAGE_OK       = 'DELETE_SECTION_IMAGE_OK'
export const DELETE_SECTION_IMAGE_ERROR    = 'DELETE_SECTION_IMAGE_ERROR'

export const ADD_SECTION_IMAGES_LIST_FETCHING = 'ADD_SECTION_IMAGES_LIST_FETCHING'
export const ADD_SECTION_IMAGES_LIST_OK       = 'ADD_SECTION_IMAGES_LIST_OK'
export const ADD_SECTION_IMAGES_LIST_ERROR    = 'ADD_SECTION_IMAGES_LIST_ERROR'


/*
    sections-list
*/
export const GET_SECTIONS_LIST_FETCHING = 'GET_SECTIONS_LIST_FETCHING'
export const GET_SECTIONS_LIST_OK       = 'GET_SECTIONS_LIST_OK'
export const GET_SECTIONS_LIST_ERROR    = 'GET_SECTIONS_LIST_ERROR'

export const ADD_SECTION_FETCHING = 'ADD_SECTION_FETCHING'
export const ADD_SECTION_OK       = 'ADD_SECTION_OK'
export const ADD_SECTION_ERROR    = 'ADD_SECTION_ERROR'

export const EDIT_SECTION_FETCHING = 'EDIT_SECTION_FETCHING'
export const EDIT_SECTION_OK       = 'EDIT_SECTION_OK'
export const EDIT_SECTION_ERROR    = 'EDIT_SECTION_ERROR'

export const DELETE_SECTION_FETCHING = 'DELETE_SECTION_FETCHING'
export const DELETE_SECTION_OK       = 'DELETE_SECTION_OK'
export const DELETE_SECTION_ERROR    = 'DELETE_SECTION_ERROR'


/*
    sign
*/
export const SIGN_IN_FETCHING = 'SIGN_IN_FETCHING'
export const SIGN_IN_OK       = 'SIGN_IN_OK'
export const SIGN_IN_ERROR    = 'SIGN_IN_ERROR'

export const SIGN_OUT_FETCHING = 'SIGN_OUT_FETCHING'
export const SIGN_OUT_OK       = 'SIGN_OUT_OK'
export const SIGN_OUT_ERROR    = 'SIGN_OUT_ERROR'

export const SIGNED_FETCHING = 'SIGNED_FETCHING'
export const SIGNED_OK       = 'SIGNED_OK'
export const SIGNED_ERROR    = 'SIGNED_ERROR'


/*
    slides-list
*/
export const GET_SLIDES_LIST_FETCHING = 'GET_SLIDES_LIST_FETCHING'
export const GET_SLIDES_LIST_OK       = 'GET_SLIDES_LIST_OK'
export const GET_SLIDES_LIST_ERROR    = 'GET_SLIDES_LIST_ERROR'

export const DELETE_SLIDE_FETCHING = 'DELETE_SLIDE_FETCHING'
export const DELETE_SLIDE_OK       = 'DELETE_SLIDE_OK'
export const DELETE_SLIDE_ERROR    = 'DELETE_SLIDE_ERROR'

export const CLEAR_SLIDES_LIST = 'CLEAR_SLIDES_LIST'

export const ADD_SLIDES_LIST_FETCHING = 'ADD_SLIDES_LIST_FETCHING'
export const ADD_SLIDES_LIST_OK       = 'ADD_SLIDES_LIST_OK'
export const ADD_SLIDES_LIST_ERROR    = 'ADD_SLIDES_LIST_ERROR'


/*
    upload-images-list
*/
export const ADD_UPLOAD_IMAGE_TO_UPLOAD_IMAGES_LIST = 'ADD_UPLOAD_IMAGE_TO_UPLOAD_IMAGES_LIST'
export const SET_UPLOAD_IMAGE_STAGE = 'SET_UPLOAD_IMAGE_STAGE'
